# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34acabf26592f05c91359e2381d2e47cd3f5507a1024c124478cec7e36526e397e67bd81826af3bd7e1735ec5c97808406ed51eb9b0e7ebc85e5514083be016

test:
  secret_key_base: ee0e08603a544959a34ac8a1088dd4133a01755d5fcedfde84fa55127a7c68b231a3f4216b55512c067b9139ca18d811b4d3850a73fa9c2e52f21b42eb6c8d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
